---
- hosts: k3s-master
  tasks:
    - name: cat hostname
      ansible.builtin.shell: |
        cat /etc/hostname
      register: cat_hostname

    - name: show cat hostname output
      ansible.builtin.debug:
        msg: |
          {{ cat_hostname.stdout_lines }}
#
#    - name: ip a
#      shell: |
#        ip a
#      register: ip_a
#
#    - name: show ip a output
#      ansible.builtin.debug:
#        msg: |
#          {{ ip_a.stdout_lines }}
