[tool.poetry]
authors = ["francojposa <franco@francoposa.io>"]
description = ""
name = "learn-ci-cd"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"
ansible = "~2.9"

[tool.poetry.dev-dependencies]
ansible = "^2.9.10"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
