[tool.poetry]
authors = ["francojposa <franco@francoposa.io>"]
description = ""
name = "learn-ci-cd"
version = "0.1.0"

[tool.poetry.dependencies]
ansible = "2.*"
python = "^3.8"

[tool.poetry.dev-dependencies]
ansible = "2.*"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
