[tool.poetry]
name = "learn-ci-cd"
version = "0.1.0"
description = ""
authors = ["francojposa <franco@francoposa.io>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
jinja2 = "^2.11.2"
ansible = "^2.9.10"
yamllint = "^1.23.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
