---
- hosts: k3s-demo-master
  vars:
    ansible_user: infra_ops
  become: yes
  tasks:
    - name: install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -s - \
          --write-kubeconfig-mode 644 \
          --tls-san {{ hostvars[inventory_hostname].ansible_host }}
    - name: replace kube config 'default' values with descriptive name
      replace:
        path: /etc/rancher/k3s/k3s.yaml
        regexp: "default"
        replace: "k3s-demo-master"
