---
- hosts: demo
  vars:
    ansible_user: infra_ops
  tasks:
    - name: copy master kube config to local
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: true
    - name: debug host ip
      debug:
        var: hostvars[inventory_hostname].ansible_host
    - name: replace kube config localhost with master ip
      replace:
        path: ~/.kube/config
        regexp: '127\.0\.0\.1'  # ansible only likes single quotes for this regex
        replace: "{{ hostvars[inventory_hostname].ansible_host }}"
      delegate_to: localhost
