apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs-volume
  labels:
    app: postgres
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 4Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "157.230.229.232"
    path: "/mnt/volume_nyc1_01/k8s/data"
