apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-nfs-volume-claim
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi