--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  annotations: 
    "storageclass.kubernetes.io/is-default-class": "true"
  name: nfs-manual
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate