---
- hosts: localhost
  tasks:
    - name: create staging cluster issuer
      kubernetes.core.k8s:
        definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          state: present
          metadata:
            name: letsencrypt-staging
            namespace: cert-manager
          spec:
            acme:
              # You must replace this email address with your own.
              # Let's Encrypt will use this to contact you about expiring
              # certificates, and issues related to your account.
              email: franco@francoposa.io
              server: https://acme-staging-v02.api.letsencrypt.org/directory
              privateKeySecretRef:
                # Secret resource that will be used to store the account's private key.
                name: letsencrypt-staging-issuer-account-key
              # Add a single challenge solver, HTTP01 using nginx
              solvers:
                - http01:
                    ingress:
                      class: traefik
