---
- hosts: localhost
  vars_prompt:
    - name: docker_password
      prompt: password for github container registry

  tasks:

    - name: create docker registry secret for github container registry
      shell: |
        kubectl create secret docker-registry \
          github-container-registry \
          --docker-server=ghcr.io \
          --docker-username=francoposa \
          --docker-password={{ docker_password }}
